### ISSUE TITLE
Get Trend Topic

### ISSUE THREAD

**Issue by HolyPeople** [2023-Konkuk-Graduation-Project-AIKU/AnswerLink#2]
## Description
Write code to fetch trending topics from the [bigkinds] site and save them in JSON format

## To-do
- [ ] Connect to [bigkinds]
- [ ] Convert `trandReportList` from a javascript variables In SITE to a JSON String.
- [ ] Save trend_topic

[bigkinds]: https://www.bigkinds.or.kr/
