### ISSUE TITLE
Get daily news

### ISSUE THREAD

**Issue by HolyPeople** [2023-Konkuk-Graduation-Project-AIKU/AnswerLink#4]
## Description
Access the site and download daily news data

## To-do
- [ ] Connect to [bigkinds]
- [ ] Search for daily news.
- [ ] Save news.xlsx

[bigkinds]: https://www.bigkinds.or.kr/
